// <auto-generated />
using System;
using AnimeShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimeShop.Migrations
{
    [DbContext(typeof(ContextAnime))]
    partial class ContextAnimeModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimeShop.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686843216/OnePiece/p12129031_b_h9_ab_okykpq.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 2,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686843215/OnePiece/8776327_so_vfd2wj.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 3,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686843215/OnePiece/v0qPfG_y7t3b7.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 4,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686843215/OnePiece/one_piece_opening_1000.jpg_423682103_p8jcjq.webp",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 5,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686843214/OnePiece/One-Piece-chapter-1_tgay9v.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            ImageId = 6,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686923807/Naruto/naruto-vol-68-9781421576824_hr_rlrggo.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 7,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686923807/Naruto/naruto1_visual_xziu06.webp",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 8,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686923806/Naruto/b12b9782aa863b75cdbee3a35ab62bd2_fy0bob.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 9,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686923806/Naruto/AAAABYxJFBDckfZw1YUEIPwyuIg43Kw_HUBLvnCcgdOlvvf5Nc90SF3HSAi5L8uLyBqjziKBY-kGD2wu2JAqVsdHVR0frb6qG26I_U5v_a9ihom.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 10,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686923806/Naruto/Profil-Picture-Naruto-Shippuden-600x600_ycugfi.webp",
                            ProductId = 2
                        },
                        new
                        {
                            ImageId = 11,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686924055/Bleach/image-asset_hoalrl.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 12,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686924055/Bleach/bleach-20th-anniversary-anime-return_cicuq1.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 13,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686924055/Bleach/3f367-16729468481724_euq3zu.avif",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 14,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686924055/Bleach/LzRDfFeNHeUCtpH-1600x900-noPad_pns11d.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 15,
                            ImageUrl = "https://res.cloudinary.com/danedskby/image/upload/v1686924055/Bleach/LzRDfFeNHeUCtpH-1600x900-noPad_pns11d.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            ImageId = 16,
                            ImageUrl = "https://cdn.vox-cdn.com/thumbor/6zsaqAYi7xeMcbhLW4MsxUN6NZs=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/3652050/wall6_wallpaper_1280x800.0.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 17,
                            ImageUrl = "https://m.media-amazon.com/images/I/71iprqtljOL._AC_UF1000,1000_QL80_.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 18,
                            ImageUrl = "https://e24joaz2t6m.exactdn.com/wp-content/uploads/2016/07/DragonBallZ-Season1-a.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 19,
                            ImageUrl = "https://www.crunchyroll.com/imgsrv/display/thumbnail/1200x675/catalog/crunchyroll/36bdc5ea4443cd8e42f22ec7d3884cbb.jpe",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 20,
                            ImageUrl = "https://assets.mycast.io/posters/dragon-ball-z-netflix-season-1-saiyan-saga-fan-casting-poster-144948-large.jpg?1636572989",
                            ProductId = 4
                        },
                        new
                        {
                            ImageId = 21,
                            ImageUrl = "https://m.media-amazon.com/images/I/81mOMGHVHdL._AC_UF1000,1000_QL80_.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 22,
                            ImageUrl = "https://i0.wp.com/boldcanon.com/wp-content/uploads/2019/09/mv5bnmqzyme2mgetzjk4ys00ymvjlwewzwmtodrkmjc4mtm5n2i3xkeyxkfqcgdeqxvyntayodkwoq4040._v1_-e1567632423552.jpg?resize=1000%2C720&ssl=1",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 23,
                            ImageUrl = "https://twinfinite.net/wp-content/uploads/2022/04/my-hero-academia-season-1-1.jpg?fit=1200%2C675",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 24,
                            ImageUrl = "https://www.screenspy.com/wp-content/uploads/2022/04/Screenshotter-MyHeroAcademiaE7DekuvsKacchan-1943.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 25,
                            ImageUrl = "https://i0.wp.com/butwhytho.net/wp-content/uploads/2022/11/My-Hero-Academia-Episode-122-But-Why-Tho-1.jpg?fit=800%2C410&ssl=1",
                            ProductId = 5
                        },
                        new
                        {
                            ImageId = 26,
                            ImageUrl = "https://static.wikia.nocookie.net/onepunchman/images/c/cd/One-Punch_Man_TV_Anime_Key_Visual.png/revision/latest?cb=20220818034817",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 27,
                            ImageUrl = "https://img4.hulu.com/user/v3/artwork/34ebf58e-5a2a-4efa-8e4d-fb16039a3051?base_image_bucket_name=image_manager&base_image=ec6b707a-85c2-4d7c-9e3d-f9adf79004e3&size=600x338&format=jpeg",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 28,
                            ImageUrl = "https://e0.pxfuel.com/wallpapers/84/241/desktop-wallpaper-one-punch-man-best-season-1-funny-saitama.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 29,
                            ImageUrl = "https://static.wikia.nocookie.net/onepunchman/images/9/99/Puri-Puri_Prisoner_vs._Deep_Sea_King.png/revision/latest?cb=20160101201537",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 30,
                            ImageUrl = "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/c5ef21697095ba7cc0bbec2c96dafca98119bac23349e0a8baac7d78a4107c07._RI_TTW_SX720_FMjpg_.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            ImageId = 31,
                            ImageUrl = "https://m.media-amazon.com/images/M/MV5BYTIxNjk3YjItYmYzMC00ZTdmLTk0NGUtZmNlZTA0NWFkZDMwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_UY1200_CR85,0,630,1200_AL_.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 32,
                            ImageUrl = "https://images.immediate.co.uk/production/volatile/sites/3/2022/10/Demon-Slayer-Attack-Different-Swords-8836587.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 33,
                            ImageUrl = "https://www.hindustantimes.com/ht-img/img/2023/04/05/1600x900/Demon_slayer_season_2_recap_1680711861129_1680711892122_1680711892122.png",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 34,
                            ImageUrl = "https://cdn.vox-cdn.com/thumbor/JBMeqrjWveSK05wPniHAOUzErrI=/1400x1050/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/24423451/Demon_Slayer_World_Tour_KV_ENG.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 35,
                            ImageUrl = "https://cdn.animenewsnetwork.com/thumbnails/max650x650/cms/news.6/192798/kimetsu_worldtour.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            ImageId = 36,
                            ImageUrl = "https://flxt.tmsimg.com/assets/p10873160_b1t_v8_aa.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 37,
                            ImageUrl = "https://2danicritic.github.io/index_files/ReviewImages/review_Attack_on_Titan_-_Season_12.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 38,
                            ImageUrl = "https://static.wikia.nocookie.net/shingekinokyojin/images/8/83/Eren_vs_Colossal_Titan.png/revision/latest?cb=20170623113218",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 39,
                            ImageUrl = "https://static.wikia.nocookie.net/shingekinokyojin/images/8/83/Eren_vs_Colossal_Titan.png/revision/latest?cb=20170623113218",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 40,
                            ImageUrl = "https://i0.wp.com/www.screenspy.com/wp-content/uploads/2022/07/attack-on-titan-s1-e25-2.png?ssl=1",
                            ProductId = 8
                        },
                        new
                        {
                            ImageId = 41,
                            ImageUrl = "https://dw9to29mmj727.cloudfront.net/promo/2016/6231-SeriesHeaders_HxH_2000x800.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 42,
                            ImageUrl = "https://static1.cbrimages.com/wordpress/wp-content/uploads/2021/06/Hunter-x-Hunter-1.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 43,
                            ImageUrl = "https://staticg.sportskeeda.com/editor/2022/04/33e84-16505291054558-1920.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 44,
                            ImageUrl = "https://www.thenewshouse.com/wp-content/uploads/Untitled-design-4-1024x683.png",
                            ProductId = 9
                        },
                        new
                        {
                            ImageId = 45,
                            ImageUrl = "https://staticg.sportskeeda.com/editor/2022/11/70a3e-16680920162796-1920.jpg",
                            ProductId = 9
                        });
                });

            modelBuilder.Entity("AnimeShop.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BillingAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AnimeShop.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("AnimeShop.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Author")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ISBN")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<string>("Platform")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Size")
                        .HasColumnType("longtext");

                    b.Property<string>("Studio")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Subtitles")
                        .HasColumnType("longtext");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Artist = "Eiichiro Oda",
                            Author = "Eiichiro Oda",
                            Category = "DVD",
                            Color = "Blue",
                            Description = "Monkey D. Luffy wants to become the King of all pirates.",
                            Duration = 750,
                            Genre = "Shonen",
                            ISBN = "123-4567891234",
                            InStock = true,
                            Language = "English",
                            Manufacturer = "Toei Animation",
                            Name = "One Piece Season 1",
                            Pages = 200,
                            Platform = "DVD",
                            Price = 29.99m,
                            Publisher = "Toei Animation",
                            Quantity = 100,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(1999, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Size = "Medium",
                            Studio = "Toei Animation",
                            Subtitles = "English",
                            TrailerUrl = "https://www.youtube.com/watch?v=UTMoDHvgaJk"
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "DVD",
                            Description = "Immerse yourself in the thrilling world of Naruto with the first box set of the iconic anime series on DVD. This box set includes the exhilarating episodes from the early seasons, introducing you to the epic journey of Naruto Uzumaki as he aspires to become the strongest ninja in his village.",
                            Duration = 840,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Naruto Box Set 1",
                            Pages = 0,
                            Price = 49.99m,
                            Publisher = "Viz Media",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2005, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "DVD",
                            Description = "The complete series of Bleach anime on DVD.",
                            Duration = 2700,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Bleach Complete Series",
                            Pages = 0,
                            Price = 149.99m,
                            Publisher = "Viz Media",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2004, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 4,
                            Category = "DVD",
                            Description = "The complete first season of Dragon Ball Z anime series on DVD.",
                            Duration = 900,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Dragon Ball Z: Season 1",
                            Pages = 0,
                            Price = 34.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(1989, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 5,
                            Category = "DVD",
                            Description = "The complete first season of My Hero Academia anime series on DVD.",
                            Duration = 325,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "My Hero Academia Season 1",
                            Pages = 0,
                            Price = 24.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2016, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 6,
                            Category = "DVD",
                            Description = "The complete first season of One Punch Man anime series on DVD.",
                            Duration = 300,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "One Punch Man Season 1",
                            Pages = 0,
                            Price = 19.99m,
                            Publisher = "Viz Media",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2015, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 7,
                            Category = "DVD",
                            Description = "The complete first season of Demon Slayer anime series on DVD.",
                            Duration = 625,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Demon Slayer Season 1",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "Aniplex",
                            Quantity = 0,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 8,
                            Category = "DVD",
                            Description = "The complete first season of Attack on Titan anime series on DVD.",
                            Duration = 625,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Attack on Titan Season 1",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2013, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 9,
                            Category = "DVD",
                            Description = "The first box set of Hunter x Hunter anime series on DVD.",
                            Duration = 675,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Hunter x Hunter Box Set 1",
                            Pages = 0,
                            Price = 59.99m,
                            Publisher = "Viz Media",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(1999, 10, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 10,
                            Category = "DVD",
                            Description = "The first collection of Fairy Tail anime series on DVD.",
                            Duration = 600,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Fairy Tail Collection 1",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.6f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2009, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 11,
                            Category = "DVD",
                            Description = "The complete first season of Yu Yu Hakusho anime series on DVD.",
                            Duration = 575,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Yu Yu Hakusho: Season 1",
                            Pages = 0,
                            Price = 34.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(1992, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 12,
                            Category = "DVD",
                            Description = "The complete first season of Black Clover anime series on DVD.",
                            Duration = 625,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Black Clover Season 1",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "Crunchyroll",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2017, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 13,
                            Category = "DVD",
                            Description = "The first part of Dragon Ball Super anime series on DVD.",
                            Duration = 325,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Dragon Ball Super: Part 1",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2015, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 14,
                            Category = "DVD",
                            Description = "The complete collection of Fullmetal Alchemist: Brotherhood anime series on DVD.",
                            Duration = 2750,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Fullmetal Alchemist: Brotherhood Complete Collection",
                            Pages = 0,
                            Price = 99.99m,
                            Publisher = "Aniplex",
                            Quantity = 0,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2009, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 15,
                            Category = "DVD",
                            Description = "The complete first season of Sword Art Online anime series on DVD.",
                            Duration = 600,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Sword Art Online: Season 1",
                            Pages = 0,
                            Price = 34.99m,
                            Publisher = "Aniplex",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2012, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 16,
                            Category = "DVD",
                            Description = "The complete first season of Fruits Basket anime series on DVD.",
                            Duration = 600,
                            Genre = "Shojo",
                            InStock = true,
                            Name = "Fruits Basket Season 1",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2001, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 17,
                            Category = "DVD",
                            Description = "A DVD collection of the Your Lie in April anime series.",
                            Duration = 550,
                            Genre = "Shojo",
                            InStock = true,
                            Name = "Your Lie in April",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "Aniplex",
                            Quantity = 0,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2014, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 18,
                            Category = "DVD",
                            Description = "The complete collection of the Nana anime series on DVD.",
                            Duration = 1150,
                            Genre = "Shojo",
                            InStock = true,
                            Name = "Nana Complete Collection",
                            Pages = 0,
                            Price = 99.99m,
                            Publisher = "Viz Media",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2006, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 19,
                            Category = "DVD",
                            Description = "A DVD set of the Princess Tutu anime series.",
                            Duration = 650,
                            Genre = "Shojo",
                            InStock = true,
                            Name = "Princess Tutu",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "ADV Films",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2002, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 20,
                            Category = "DVD",
                            Description = "The complete first season of the Kimi ni Todoke anime series on DVD.",
                            Duration = 625,
                            Genre = "Shojo",
                            InStock = true,
                            Name = "Kimi ni Todoke Season 1",
                            Pages = 0,
                            Price = 34.99m,
                            Publisher = "NIS America",
                            Quantity = 0,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2009, 10, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 21,
                            Category = "DVD",
                            Description = "The complete first season of Attack on Titan anime series on DVD.",
                            Duration = 625,
                            Genre = "Seinen",
                            InStock = true,
                            Name = "Attack on Titan Season 1",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2013, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 22,
                            Category = "DVD",
                            Description = "The complete first season of Tokyo Ghoul anime series on DVD.",
                            Duration = 300,
                            Genre = "Seinen",
                            InStock = true,
                            Name = "Tokyo Ghoul Season 1",
                            Pages = 0,
                            Price = 24.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2014, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 23,
                            Category = "DVD",
                            Description = "A DVD collection of the Death Note anime series.",
                            Duration = 675,
                            Genre = "Seinen",
                            InStock = true,
                            Name = "Death Note",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "Viz Media",
                            Quantity = 0,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2006, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 24,
                            Category = "DVD",
                            Description = "The complete series of the Cowboy Bebop anime on DVD.",
                            Duration = 1175,
                            Genre = "Seinen",
                            InStock = true,
                            Name = "Cowboy Bebop Complete Series",
                            Pages = 0,
                            Price = 49.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(1998, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 25,
                            Category = "DVD",
                            Description = "The complete collection of the Parasyte -the maxim- anime series on DVD.",
                            Duration = 625,
                            Genre = "Seinen",
                            InStock = true,
                            Name = "Parasyte -the maxim- Complete Collection",
                            Pages = 0,
                            Price = 59.99m,
                            Publisher = "Sentai Filmworks",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2014, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 26,
                            Category = "DVD",
                            Description = "The complete series of the Nodame Cantabile anime on DVD.",
                            Duration = 1325,
                            Genre = "Josei",
                            InStock = true,
                            Name = "Nodame Cantabile Complete Series",
                            Pages = 0,
                            Price = 79.99m,
                            Publisher = "Geneon Universal Entertainment",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2007, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 27,
                            Category = "DVD",
                            Description = "A DVD collection of the Honey and Clover anime series.",
                            Duration = 850,
                            Genre = "Josei",
                            InStock = true,
                            Name = "Honey and Clover",
                            Pages = 0,
                            Price = 49.99m,
                            Publisher = "Viz Media",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2005, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 28,
                            Category = "DVD",
                            Description = "The complete first season of the Chihayafuru anime series on DVD.",
                            Duration = 625,
                            Genre = "Josei",
                            InStock = true,
                            Name = "Chihayafuru Season 1",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "Madhouse",
                            Quantity = 0,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2011, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 29,
                            Category = "DVD",
                            Description = "The complete collection of the Nana anime series on DVD.",
                            Duration = 1150,
                            Genre = "Josei",
                            InStock = true,
                            Name = "Nana Complete Collection",
                            Pages = 0,
                            Price = 99.99m,
                            Publisher = "Viz Media",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2006, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 30,
                            Category = "DVD",
                            Description = "A DVD set of the Paradise Kiss anime series.",
                            Duration = 325,
                            Genre = "Josei",
                            InStock = true,
                            Name = "Paradise Kiss",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "Geneon Universal Entertainment",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2005, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 31,
                            Category = "DVD",
                            Description = "The complete Indigo League season of the Pokémon anime series on DVD.",
                            Duration = 1175,
                            Genre = "Kodomomuke",
                            InStock = true,
                            Name = "Pokémon Indigo League",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "Viz Media",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(1997, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 32,
                            Category = "DVD",
                            Description = "A DVD collection of Doraemon episodes.",
                            Duration = 325,
                            Genre = "Kodomomuke",
                            InStock = true,
                            Name = "Doraemon: Gadget Cat from the Future",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "Shin-Ei Animation",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(1979, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 33,
                            Category = "DVD",
                            Description = "The complete first season of the Sailor Moon anime series on DVD.",
                            Duration = 625,
                            Genre = "Kodomomuke",
                            InStock = true,
                            Name = "Sailor Moon Season 1",
                            Pages = 0,
                            Price = 49.99m,
                            Publisher = "Viz Media",
                            Quantity = 0,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(1992, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 34,
                            Category = "DVD",
                            Description = "The complete first season of the Yo-kai Watch anime series on DVD.",
                            Duration = 525,
                            Genre = "Kodomomuke",
                            InStock = true,
                            Name = "Yo-kai Watch Season 1",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "Level-5",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2014, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 35,
                            Category = "DVD",
                            Description = "The complete first season of the Detective Conan anime series on DVD.",
                            Duration = 625,
                            Genre = "Kodomomuke",
                            InStock = true,
                            Name = "Detective Conan Season 1",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "TMS Entertainment",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(1996, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 36,
                            Category = "DVD",
                            Description = "The complete first season of Sword Art Online anime series on DVD.",
                            Duration = 600,
                            Genre = "Isekai",
                            InStock = true,
                            Name = "Sword Art Online Season 1",
                            Pages = 0,
                            Price = 34.99m,
                            Publisher = "Aniplex",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2012, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 37,
                            Category = "DVD",
                            Description = "The complete first season of Overlord anime series on DVD.",
                            Duration = 325,
                            Genre = "Isekai",
                            InStock = true,
                            Name = "Overlord Season 1",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2015, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 38,
                            Category = "DVD",
                            Description = "The complete first season of Re:Zero anime series on DVD.",
                            Duration = 625,
                            Genre = "Isekai",
                            InStock = true,
                            Name = "Re:Zero Season 1",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "Crunchyroll",
                            Quantity = 0,
                            Rating = 4.9f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2016, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 39,
                            Category = "DVD",
                            Description = "The complete first season of Konosuba anime series on DVD.",
                            Duration = 300,
                            Genre = "Isekai",
                            InStock = true,
                            Name = "Konosuba Season 1",
                            Pages = 0,
                            Price = 24.99m,
                            Publisher = "Crunchyroll",
                            Quantity = 0,
                            Rating = 4.8f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2016, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 40,
                            Category = "DVD",
                            Description = "The complete first season of The Rising of the Shield Hero anime series on DVD.",
                            Duration = 625,
                            Genre = "Isekai",
                            InStock = true,
                            Name = "The Rising of the Shield Hero Season 1",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "Crunchyroll",
                            Quantity = 0,
                            Rating = 4.7f,
                            Region = "Region 1",
                            ReleaseDate = new DateTime(2019, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Subtitles = "English"
                        },
                        new
                        {
                            ProductId = 41,
                            Category = "Merchandise",
                            Description = "Hoodie featuring the Attack on Titan logo.",
                            Duration = 0,
                            Genre = "Seinen",
                            InStock = true,
                            Name = "Attack on Titan Hoodie",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "Kodansha",
                            Quantity = 0,
                            Rating = 4.8f,
                            ReleaseDate = new DateTime(2009, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 42,
                            Category = "Merchandise",
                            Description = "Set of keychains featuring the characters from My Hero Academia.",
                            Duration = 0,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "My Hero Academia Keychain Set",
                            Pages = 0,
                            Price = 14.99m,
                            Publisher = "Funimation",
                            Quantity = 0,
                            Rating = 4.8f,
                            ReleaseDate = new DateTime(2016, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 43,
                            Category = "Merchandise",
                            Description = "Authentic Naruto headband worn by the ninjas of the Hidden Leaf Village.",
                            Duration = 0,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Naruto Headband",
                            Pages = 0,
                            Price = 19.99m,
                            Publisher = "Shueisha",
                            Quantity = 0,
                            Rating = 4.7f,
                            ReleaseDate = new DateTime(1999, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 44,
                            Category = "Merchandise",
                            Description = "T-Shirt featuring the Demon Slayer logo.",
                            Duration = 0,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Demon Slayer T-Shirt",
                            Pages = 0,
                            Price = 24.99m,
                            Publisher = "Aniplex",
                            Quantity = 0,
                            Rating = 4.9f,
                            ReleaseDate = new DateTime(2019, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 45,
                            Category = "Merchandise",
                            Description = "Backpack featuring the Fairy Tail guild emblem.",
                            Duration = 0,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Fairy Tail Backpack",
                            Pages = 0,
                            Price = 39.99m,
                            Publisher = "Kodansha",
                            Quantity = 0,
                            Rating = 4.7f,
                            ReleaseDate = new DateTime(2006, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 46,
                            Category = "Merchandise",
                            Description = "Set of plushies featuring the characters from Sailor Moon.",
                            Duration = 0,
                            Genre = "Shojo",
                            InStock = true,
                            Name = "Sailor Moon Plushies Set",
                            Pages = 0,
                            Price = 29.99m,
                            Publisher = "Kodansha",
                            Quantity = 0,
                            Rating = 4.8f,
                            ReleaseDate = new DateTime(1992, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 47,
                            Category = "Merchandise",
                            Description = "Mug featuring the Tokyo Ghoul logo.",
                            Duration = 0,
                            Genre = "Seinen",
                            InStock = true,
                            Name = "Tokyo Ghoul Mug",
                            Pages = 0,
                            Price = 14.99m,
                            Publisher = "Shueisha",
                            Quantity = 0,
                            Rating = 4.6f,
                            ReleaseDate = new DateTime(2011, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 48,
                            Category = "Merchandise",
                            Description = "Keychain featuring the Attack on Titan Survey Corps emblem.",
                            Duration = 0,
                            Genre = "Seinen",
                            InStock = true,
                            Name = "Attack on Titan Keychain",
                            Pages = 0,
                            Price = 9.99m,
                            Publisher = "Kodansha",
                            Quantity = 0,
                            Rating = 4.7f,
                            ReleaseDate = new DateTime(2009, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 49,
                            Category = "Merchandise",
                            Description = "Poster featuring the characters from Haikyu!!.",
                            Duration = 0,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Haikyu!! Poster",
                            Pages = 0,
                            Price = 9.99m,
                            Publisher = "Shueisha",
                            Quantity = 0,
                            Rating = 4.8f,
                            ReleaseDate = new DateTime(2012, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 50,
                            Category = "Merchandise",
                            Description = "Music box playing the theme song from Your Lie in April.",
                            Duration = 0,
                            Genre = "Shojo",
                            InStock = true,
                            Name = "Your Lie in April Music Box",
                            Pages = 0,
                            Price = 34.99m,
                            Publisher = "Kodansha",
                            Quantity = 0,
                            Rating = 4.9f,
                            ReleaseDate = new DateTime(2011, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 51,
                            Category = "Apparel",
                            Description = "Hoodie featuring the Attack on Titan Survey Corps emblem.",
                            Duration = 0,
                            Genre = "Seinen",
                            InStock = true,
                            Name = "Attack on Titan Hoodie",
                            Pages = 0,
                            Price = 49.99m,
                            Publisher = "Kodansha",
                            Quantity = 0,
                            Rating = 4.8f,
                            ReleaseDate = new DateTime(2009, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 52,
                            Category = "Apparel",
                            Description = "T-Shirt featuring Naruto Uzumaki artwork.",
                            Duration = 0,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "Naruto T-Shirt",
                            Pages = 0,
                            Price = 19.99m,
                            Publisher = "Shueisha",
                            Quantity = 0,
                            Rating = 4.7f,
                            ReleaseDate = new DateTime(1999, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 53,
                            Category = "Apparel",
                            Description = "Sweatshirt featuring the Sailor Moon logo.",
                            Duration = 0,
                            Genre = "Shojo",
                            InStock = true,
                            Name = "Sailor Moon Sweatshirt",
                            Pages = 0,
                            Price = 34.99m,
                            Publisher = "Kodansha",
                            Quantity = 0,
                            Rating = 4.9f,
                            ReleaseDate = new DateTime(1992, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 54,
                            Category = "Apparel",
                            Description = "Cap featuring the One Piece Jolly Roger emblem.",
                            Duration = 0,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "One Piece Cap",
                            Pages = 0,
                            Price = 14.99m,
                            Publisher = "Shueisha",
                            Quantity = 0,
                            Rating = 4.8f,
                            ReleaseDate = new DateTime(1997, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 55,
                            Category = "Apparel",
                            Description = "Set of socks featuring characters from My Hero Academia.",
                            Duration = 0,
                            Genre = "Shonen",
                            InStock = true,
                            Name = "My Hero Academia Socks Set",
                            Pages = 0,
                            Price = 9.99m,
                            Publisher = "Shueisha",
                            Quantity = 0,
                            Rating = 4.7f,
                            ReleaseDate = new DateTime(2014, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AnimeShop.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AnimeShop.Models.ShoppingCartItem", b =>
                {
                    b.Property<int>("ShoppingCartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ShoppingCartItemId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("State")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AnimeShop.Models.Image", b =>
                {
                    b.HasOne("AnimeShop.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AnimeShop.Models.Order", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeShop.Models.OrderItem", b =>
                {
                    b.HasOne("AnimeShop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnimeShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AnimeShop.Models.Review", b =>
                {
                    b.HasOne("AnimeShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnimeShop.Models.ShoppingCartItem", b =>
                {
                    b.HasOne("AnimeShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimeShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("AnimeShop.Models.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
